//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _5032Project_v2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int AppointmentId { get; set; }
        public string UserId { get; set; }
        public System.DateTime DateTime { get; set; }
        public int Status { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
